# Generated by Django 4.0.1 on 2022-01-28 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Project name')),
                ('initialDateTime', models.DateTimeField(verbose_name='Initial Period')),
                ('finalDateTime', models.DateTimeField(verbose_name='Initial Period')),
                ('limitingMagnitude', models.DecimalField(decimal_places=2, default=18, max_digits=10, verbose_name='Limiting Magnitude')),
                ('searchStep', models.IntegerField(default=7, verbose_name='Search Step')),
                ('segments', models.IntegerField(default=8, verbose_name='Segments')),
                ('automaticSegments', models.BooleanField(default=True, verbose_name='Automatic')),
                ('catalog', models.CharField(max_length=50, verbose_name='Catalog')),
                ('offEarthSigma', models.IntegerField(default=1, verbose_name='Off Earth Sigma')),
                ('radius', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Radius')),
                ('referenceCenter', models.CharField(choices=[('GC', 'Geocenter'), ('SC', 'Space Craft')], default='GC', max_length=2, verbose_name='Reference Center')),
                ('referenceCenterBSPzipFile', models.BinaryField(default=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ephemeris', models.CharField(choices=[('JPL', 'JPL/Horizons'), ('BSP', 'Custom BSP Files')], default='JPL', max_length=3, verbose_name='Ephemeris')),
                ('ephemerisBSPzipFile', models.BinaryField(default=None)),
                ('idProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
