# Generated by Django 4.0.1 on 2022-01-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='catalog',
            field=models.CharField(default='gaiaedr3', max_length=50, verbose_name='Catalog'),
        ),
        migrations.AlterField(
            model_name='project',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Radius'),
        ),
    ]
