# Generated by Django 4.0.1 on 2022-01-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_catalog_alter_project_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='ephemerisBSPzipFile',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='referenceCenterBSPzipFile',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
