# Generated by Django 4.0.2 on 2022-02-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_finaldatetime_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='endAt',
        ),
        migrations.AddField(
            model_name='job',
            name='endedAt',
            field=models.DateTimeField(null=True, verbose_name='Ended At'),
        ),
        migrations.AlterField(
            model_name='job',
            name='params',
            field=models.JSONField(null=True, verbose_name='Params'),
        ),
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.JSONField(null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='job',
            name='startedAt',
            field=models.DateTimeField(null=True, verbose_name='Started At'),
        ),
    ]
