# Generated by Django 4.0.2 on 2022-04-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_lightcurve'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
