# Generated by Django 4.0.2 on 2022-04-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_centralbandpass_lightcurve_centralbandpass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='graficalEmersion',
            field=models.TextField(default=None, null=True, verbose_name='GraficalEmersion'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='graficalFlux',
            field=models.TextField(default=None, null=True, verbose_name='GraficalFlux'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='graficalImmersion',
            field=models.TextField(default=None, null=True, verbose_name='GraficalImmersion'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='graficalModel',
            field=models.TextField(default=None, null=True, verbose_name='GraficalModel'),
        ),
    ]
