# Generated by Django 4.0.2 on 2022-04-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_project_radius_body_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='taskGuidTask',
            field=models.UUIDField(default=None, null=True, verbose_name='TaskGuidTask'),
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='exposureTime',
            field=models.FloatField(null=True, verbose_name='ExposureTime'),
        ),
    ]
