# Generated by Django 4.0.4 on 2022-05-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_prediction_starcode_star'),
        ('api', '0021_remove_lightcurve_centralbandpass_and_more'),
    ]

    operations = [
    ]
