# Generated by Django 4.0.4 on 2022-05-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20220512_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='offset',
        ),
        migrations.AddField(
            model_name='star',
            name='da_cosdec',
            field=models.FloatField(default=0, verbose_name='da_cosdec'),
        ),
        migrations.AddField(
            model_name='star',
            name='ddec',
            field=models.FloatField(default=0, verbose_name='ddec'),
        ),
    ]
