# Generated by Django 4.0.4 on 2022-05-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_star_offset_star_da_cosdec_star_ddec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='calculationType',
            field=models.CharField(choices=[('kervella', 'kervella'), ('van_belle', 'van_belle'), ('catalog', 'catalog'), ('manual', 'manual')], default=None, max_length=9, null=True, verbose_name='CalculationType'),
        ),
        migrations.AlterField(
            model_name='star',
            name='vanBelleType',
            field=models.CharField(choices=[('sg', 'sg'), ('ms', 'ms'), ('vs', 'vs')], default=None, max_length=2, null=True, verbose_name='VanBelleType'),
        ),
    ]
