# Generated by Django 4.0.4 on 2022-05-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_star_radvel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='da_cosdec',
            field=models.FloatField(default=0, null=True, verbose_name='da_cosdec'),
        ),
        migrations.AlterField(
            model_name='star',
            name='ddec',
            field=models.FloatField(default=0, null=True, verbose_name='ddec'),
        ),
        migrations.AlterField(
            model_name='star',
            name='diameter',
            field=models.FloatField(default=0, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='star',
            name='radVel',
            field=models.FloatField(default=0, null=True, verbose_name='radVel'),
        ),
        migrations.AlterField(
            model_name='star',
            name='varB',
            field=models.FloatField(default=0, null=True, verbose_name='varB'),
        ),
        migrations.AlterField(
            model_name='star',
            name='varK',
            field=models.FloatField(default=0, null=True, verbose_name='varK'),
        ),
        migrations.AlterField(
            model_name='star',
            name='varV',
            field=models.FloatField(default=0, null=True, verbose_name='varV'),
        ),
    ]
