# Generated by Django 4.0.2 on 2022-05-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_star_da_cosdec_alter_star_ddec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='radius',
            field=models.FloatField(null=True, verbose_name='Radius'),
        ),
        migrations.AlterField(
            model_name='star',
            name='calculationType',
            field=models.CharField(choices=[('kervella', 'kervella'), ('van_belle', 'van_belle'), ('gaia', 'gaia'), ('user', 'user')], default=None, max_length=9, null=True, verbose_name='CalculationType'),
        ),
    ]
