# Generated by Django 4.0.2 on 2022-06-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_lightcurve_maxduration_lightcurve_numdetections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='vanBelleType',
        ),
        migrations.AddField(
            model_name='star',
            name='starType',
            field=models.CharField(choices=[('sg', 'sg'), ('ms', 'ms'), ('vs', 'vs')], default=None, max_length=2, null=True, verbose_name='StarType'),
        ),
    ]
