# Generated by Django 4.0.4 on 2022-07-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_lightcurve_taskguidtask_lightcurve_taskid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ellipse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerF', models.FloatField(verbose_name='centerF')),
                ('centerG', models.FloatField(verbose_name='centerG')),
                ('equatorialRadius', models.FloatField(verbose_name='equatorialRadius')),
                ('oblateness', models.FloatField(verbose_name='oblateness')),
                ('positionAngle', models.FloatField(verbose_name='positionAngle')),
                ('dCenterF', models.FloatField(verbose_name='dCenterF')),
                ('dCenterG', models.FloatField(verbose_name='dCenterG')),
                ('dEquatorialRadius', models.FloatField(verbose_name='dEquatorialRadius')),
                ('dOblateness', models.FloatField(verbose_name='dOblateness')),
                ('dPositionAngle', models.FloatField(verbose_name='dPositionAngle')),
                ('loop', models.IntegerField(verbose_name='loop')),
                ('dChiMin', models.FloatField(verbose_name='dChiMin')),
                ('numberChi', models.IntegerField(verbose_name='numberChi')),
                ('ellipseError', models.FloatField(verbose_name='ellipseError')),
                ('sigmaResult', models.FloatField(verbose_name='sigmaResult')),
                ('allEllipses', models.BooleanField(verbose_name='allEllipses')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prediction')),
            ],
        ),
    ]
