# Generated by Django 4.0.4 on 2022-07-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_ellipse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ellipse',
            name='allEllipses',
            field=models.BooleanField(null=True, verbose_name='allEllipses'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='dCenterF',
            field=models.FloatField(null=True, verbose_name='dCenterF'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='dCenterG',
            field=models.FloatField(null=True, verbose_name='dCenterG'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='dChiMin',
            field=models.FloatField(null=True, verbose_name='dChiMin'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='dEquatorialRadius',
            field=models.FloatField(null=True, verbose_name='dEquatorialRadius'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='dOblateness',
            field=models.FloatField(null=True, verbose_name='dOblateness'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='dPositionAngle',
            field=models.FloatField(null=True, verbose_name='dPositionAngle'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='ellipseError',
            field=models.FloatField(null=True, verbose_name='ellipseError'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='loop',
            field=models.IntegerField(null=True, verbose_name='loop'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='numberChi',
            field=models.IntegerField(null=True, verbose_name='numberChi'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='sigmaResult',
            field=models.FloatField(null=True, verbose_name='sigmaResult'),
        ),
    ]
