# Generated by Django 4.0.2 on 2022-07-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_lightcurve_negative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='ephemeris',
            field=models.CharField(choices=[('JPL', 'JPL/Horizons'), ('BSP', 'Custom BSP Files')], default='JPL', max_length=3, null=True, verbose_name='Ephemeris'),
        ),
    ]
