#!/bin/sh

prefix=C:/Users/user/.conda/envs/asyncqueuetasks/Library
exec_prefix=C:/Users/user/.conda/envs/asyncqueuetasks/Library/bin
libdir=C:/Users/user/.conda/envs/asyncqueuetasks/Library/lib

usage()
{
    cat <<EOF
Usage: geos-config [OPTIONS]
Options:
     [--prefix]
     [--version]
     [--libs]
     [--clibs]
     [--cclibs]
     [--static-clibs]
     [--static-cclibs]
     [--cflags]
     [--ldflags]
     [--includes]
     [--jtsport]
EOF
    exit $1
}

if test $# -eq 0; then
  usage 1 1>&2
fi

while test $# -gt 0; do
case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
esac
case $1 in
    --prefix)
      echo C:/Users/user/.conda/envs/asyncqueuetasks/Library
      ;;
    --version)
      echo 3.8.0
      ;;
    --cflags)
      echo -IC:/Users/user/.conda/envs/asyncqueuetasks/Library/include
      ;;
    --libs)
      echo -LC:/Users/user/.conda/envs/asyncqueuetasks/Library/lib -lgeos-3
      ;;
    --clibs)
      echo -LC:/Users/user/.conda/envs/asyncqueuetasks/Library/lib -lgeos_c
      ;;
    --cclibs)
      echo -LC:/Users/user/.conda/envs/asyncqueuetasks/Library/lib -lgeos
      ;;
    --static-clibs)
      echo -LC:/Users/user/.conda/envs/asyncqueuetasks/Library/lib -lgeos_c -lgeos -lm
      ;;
    --static-cclibs)
      echo -LC:/Users/user/.conda/envs/asyncqueuetasks/Library/lib -lgeos -lm
      ;;
    --ldflags)
      echo -LC:/Users/user/.conda/envs/asyncqueuetasks/Library/lib -lgeos
      ;;
    --includes)
      echo C:/Users/user/.conda/envs/asyncqueuetasks/Library/include
      ;;
    --jtsport)
    echo 1.13.0
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

