# Generated by Django 4.0.2 on 2022-02-17 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, default=None, max_length=60, null=True, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Project name')),
                ('initialDateTime', models.DateTimeField(verbose_name='Initial Period')),
                ('finalDateTime', models.DateTimeField(verbose_name='Initial Period')),
                ('limitingMagnitude', models.DecimalField(decimal_places=2, default=18, max_digits=10, verbose_name='Limiting Magnitude')),
                ('searchStep', models.IntegerField(default=7, verbose_name='Search Step')),
                ('segments', models.IntegerField(default=8, verbose_name='Segments')),
                ('automaticSegments', models.BooleanField(default=True, verbose_name='Automatic')),
                ('catalog', models.CharField(default='gaiaedr3', max_length=50, verbose_name='Catalog')),
                ('offEarthSigma', models.IntegerField(default=1, verbose_name='Off Earth Sigma')),
                ('radius', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Radius')),
                ('referenceCenter', models.CharField(choices=[('GC', 'Geocenter'), ('SC', 'Space Craft')], default='GC', max_length=2, verbose_name='Reference Center')),
                ('referenceCenterBSPzipFile', models.BinaryField(default=None, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bodyName', models.CharField(max_length=50, verbose_name='Body Name')),
                ('ephemeris', models.CharField(choices=[('JPL', 'JPL/Horizons'), ('BSP', 'Custom BSP Files')], default='JPL', max_length=3, verbose_name='Ephemeris')),
                ('ephemerisBSPzipFile', models.BinaryField(default=None, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
