# Generated by Django 4.0.2 on 2022-02-23 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finalDateTime',
            field=models.DateTimeField(verbose_name='Final Period'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Job name')),
                ('params', models.JSONField(verbose_name='Params')),
                ('result', models.JSONField(verbose_name='Result')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('startedAt', models.DateTimeField(verbose_name='Started At')),
                ('endAt', models.DateTimeField(verbose_name='End At')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='QUEUED', max_length=7, verbose_name='Status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
