# Generated by Django 4.0.2 on 2022-04-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_prediction_dist_prediction_vel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataFile', models.TextField(verbose_name='DataFile')),
                ('timeColumnIndex', models.IntegerField(verbose_name='TimeColumnIndex')),
                ('fluxColumnIndex', models.IntegerField(verbose_name='FluxColumnIndex')),
                ('fluxErrorColumnIndex', models.IntegerField(verbose_name='FluxErrorColumnIndex')),
                ('velocity', models.FloatField(verbose_name='Velocity')),
                ('velocityUnity', models.CharField(default=None, max_length=4, verbose_name='VelocityUnity')),
                ('distance', models.FloatField(verbose_name='Distance')),
                ('distanceUnity', models.CharField(default=None, max_length=2, verbose_name='DistanceUnity')),
                ('diameter', models.FloatField(verbose_name='Diameter')),
                ('diameterUnity', models.CharField(default=None, max_length=2, verbose_name='DiameterUnity')),
                ('referenceDate', models.DateTimeField(null=True, verbose_name='Ended At')),
                ('timeFormat', models.CharField(choices=[('Julian', 'Julian'), ('Seconds', 'Seconds')], default='Julian', max_length=7, verbose_name='TimeFormat')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prediction')),
            ],
        ),
    ]
