# Generated by Django 4.0.2 on 2022-04-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_prediction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='CentralBandpass',
            field=models.FloatField(null=True, verbose_name='DeltaBandpass'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='DeltaBandpass',
            field=models.FloatField(null=True, verbose_name='DeltaBandpass'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='Detection',
            field=models.FloatField(null=True, verbose_name='Detection'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='EmersionError',
            field=models.FloatField(null=True, verbose_name='EmersionError'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='EmersionTime',
            field=models.DateTimeField(null=True, verbose_name='EmersionTime'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='EndTime',
            field=models.DateTimeField(null=True, verbose_name='EndTime'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='ExposureTime',
            field=models.DateTimeField(null=True, verbose_name='ExposureTime'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='ImmersionError',
            field=models.FloatField(null=True, verbose_name='ImmersionError'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='ImmersionTime',
            field=models.DateTimeField(null=True, verbose_name='ImmersionTime'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='InitialTime',
            field=models.DateTimeField(null=True, verbose_name='InitialTime'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='TimeRef',
            field=models.DateTimeField(null=True, verbose_name='TimeRef'),
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='referenceDate',
            field=models.DateTimeField(null=True, verbose_name='referenceDate'),
        ),
    ]
