# Generated by Django 4.0.2 on 2022-04-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_lightcurve_graficalemersion_lightcurve_graficalflux_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='radius',
        ),
        migrations.AddField(
            model_name='body',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Radius'),
        ),
    ]
