# Generated by Django 4.0.2 on 2022-05-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_star_calculationtype_alter_star_vanbelletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='json',
            field=models.TextField(default=None, null=True, verbose_name='GraficalModel'),
        ),
    ]
