# Generated by Django 4.0.4 on 2022-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_lightcurve_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='radVel',
            field=models.FloatField(default=0, verbose_name='radVel'),
        ),
    ]
