# Generated by Django 4.0.2 on 2022-05-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_body_radius_alter_star_calculationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='graficalModelEmersion',
            field=models.TextField(default=None, null=True, verbose_name='GraficalModel'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='graficalModelImmersion',
            field=models.TextField(default=None, null=True, verbose_name='GraficalModel'),
        ),
    ]
