# Generated by Django 4.0.2 on 2022-06-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_lightcurve_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='referenceMag',
            field=models.CharField(default='', max_length=1, verbose_name='referenceMag'),
        ),
        migrations.AddField(
            model_name='star',
            name='varG',
            field=models.FloatField(default=0, null=True, verbose_name='varG'),
        ),
        migrations.AlterField(
            model_name='star',
            name='calculationType',
            field=models.CharField(choices=[('kervella', 'kervella'), ('van_belle', 'van_belle'), ('gaiaedr3', 'gaiaedr3'), ('user', 'user')], default=None, max_length=9, null=True, verbose_name='CalculationType'),
        ),
    ]
