# Generated by Django 4.0.4 on 2022-06-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_star_calculationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='maxDuration',
            field=models.FloatField(default=None, null=True, verbose_name='MaximumDuration'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='numDetections',
            field=models.FloatField(default=None, null=True, verbose_name='NumberDetection'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='snrLimit',
            field=models.FloatField(default=None, null=True, verbose_name='SNRLimit'),
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='stepSize',
            field=models.FloatField(default=None, null=True, verbose_name='StepSize'),
        ),
    ]
