# Generated by Django 4.0.4 on 2022-06-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_lightcurve_maxduration_lightcurve_numdetections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightcurve',
            name='fluxMax',
            field=models.FloatField(null=True, verbose_name='FluxMax'),
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='fluxMin',
            field=models.FloatField(null=True, verbose_name='FluxMin'),
        ),
    ]
