# Generated by Django 4.0.4 on 2022-06-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_lightcurve_fluxmax_alter_lightcurve_fluxmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightcurve',
            name='dopacity',
            field=models.FloatField(null=True, verbose_name='Dopacity'),
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='loop',
            field=models.IntegerField(null=True, verbose_name='Loop'),
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='opacity',
            field=models.FloatField(null=True, verbose_name='Opacity'),
        ),
    ]
