# Generated by Django 4.0.4 on 2022-06-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_lightcurve_dopacity_alter_lightcurve_loop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='graficalOpacity',
            field=models.TextField(default=None, null=True, verbose_name='GraficalOpacity'),
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='graficalModelEmersion',
            field=models.TextField(default=None, null=True, verbose_name='GraficalModelEmersion'),
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='graficalModelImmersion',
            field=models.TextField(default=None, null=True, verbose_name='GraficalModelImmersion'),
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='json',
            field=models.TextField(default=None, null=True, verbose_name='Json'),
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='referenceDate',
            field=models.DateTimeField(null=True, verbose_name='ReferenceDate'),
        ),
    ]
