# Generated by Django 4.0.4 on 2022-06-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_lightcurve_file1result_lightcurve_file2result_and_more'),
        ('api', '0038_lightcurve_graficalopacity_and_more'),
    ]

    operations = [
    ]
