# Generated by Django 4.0.4 on 2022-06-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_merge_20220615_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightcurve',
            name='detection',
        ),
        migrations.RemoveField(
            model_name='lightcurve',
            name='timeRef',
        ),
    ]
