# Generated by Django 4.0.4 on 2022-06-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_observer_latitude_alter_observer_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightcurve',
            name='taskGuidTask',
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='taskId',
            field=models.UUIDField(default=None, null=True, verbose_name='TaskId'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='graficalOccultation',
            field=models.TextField(default=None, null=True, verbose_name='Grafical'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='taskId',
            field=models.UUIDField(default=None, null=True, verbose_name='TaskId'),
        ),
    ]
