# Generated by Django 4.0.4 on 2022-07-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_prediction_ellipse_chi2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ellipse',
            name='negativeChord',
            field=models.CharField(max_length=50, null=True, verbose_name='Negative Chord'),
        ),
        migrations.AddField(
            model_name='ellipse',
            name='sigma',
            field=models.FloatField(null=True, verbose_name='Sigma'),
        ),
        migrations.AddField(
            model_name='ellipse',
            name='step',
            field=models.FloatField(max_length=8, null=True, verbose_name='Step'),
        ),
    ]
