# Generated by Django 4.0.4 on 2022-07-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_lightcurve_taskid_remove_prediction_taskid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ellipse',
            name='centerF',
            field=models.FloatField(null=True, verbose_name='centerF'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='centerG',
            field=models.FloatField(null=True, verbose_name='centerG'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='equatorialRadius',
            field=models.FloatField(null=True, verbose_name='equatorialRadius'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='oblateness',
            field=models.FloatField(null=True, verbose_name='oblateness'),
        ),
        migrations.AlterField(
            model_name='ellipse',
            name='positionAngle',
            field=models.FloatField(null=True, verbose_name='positionAngle'),
        ),
    ]
